### ISSUE TITLE
game is permanently on my arduboy.

### ISSUE THREAD

**Issue by alldaytaytay** [MLXXXp/ArduboyLife#2]
i cannot install a new game on my arduboy. it always loads this game. i dont know if it is a flaw in the arduboy itself, but its always happening.

**Comment by MLXXXp** [comment]
This game uses a large amount of RAM an can expose a flaw in the bootloader. See this article on the Arduboy forum:
http://community.arduboy.com/t/arduboy-gets-a-life-conways-game-of-life/578/10
